apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
        - name: jenkins-demo
          image: asia-southeast1-docker.pkg.dev/YOUR_GCP_PROJECT_ID/jenkins-demo/jenkins-demo:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins-demo
  ports:
    - port: 80
      targetPort: 8080
